# Generated by Django 3.1.1 on 2020-11-26 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201126_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='id',
            new_name='user_id',
        ),
    ]
