# Generated by Django 3.1.3 on 2020-11-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201126_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], default='F', max_length=1),
        ),
    ]
