# Generated by Django 3.1.1 on 2020-11-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('shaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('idmembre', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.member')),
            ],
            options={
                'db_table': 'FAVORI',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('intitule', models.CharField(db_column='INTITULE', max_length=255)),
                ('degrealcool', models.IntegerField(blank=True, db_column='DEGREALCOOL', null=True)),
            ],
            options={
                'db_table': 'INGREDIENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Noter',
            fields=[
                ('idmembre', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.member')),
                ('note', models.IntegerField(db_column='NOTE')),
            ],
            options={
                'db_table': 'NOTER',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('idmembre', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='user.member')),
            ],
            options={
                'db_table': 'PREFERENCE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propose',
            fields=[
                ('idpropose', models.IntegerField(db_column='IDPROPOSE', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'PROPOSE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stocker',
            fields=[
                ('idstocker', models.IntegerField(db_column='IDSTOCKER', primary_key=True, serialize=False)),
                ('enreserve', models.BooleanField(db_column='ENRESERVE')),
            ],
            options={
                'db_table': 'STOCKER',
                'managed': False,
            },
        ),
    ]
