# Generated by Django 3.1.3 on 2020-11-26 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_member_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='id_hote',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
