# Generated by Django 3.1.3 on 2020-11-26 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201126_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='id',
        ),
    ]
