DROP DATABASE pts3;
CREATE DATABASE pts3;
USE pts3;

ALTER DATABASE pts3 CHARACTER SET utf8 COLLATE utf8_unicode_ci;

CREATE TABLE COMPTE
        (ID INT(4) PRIMARY KEY,
         LOGIN VARCHAR(32) UNIQUE NOT NULL,
         PASSHASH VARCHAR(255) NOT NULL,
         EMAIL VARCHAR(255) UNIQUE NOT NULL,
         DATECREATION DATE,
         DERNIERECONNEXION DATE,
         ENLIGNE TINYINT(1) NOT NULL,
         SESSIONID VARCHAR(20) UNIQUE,
		 	IDMEMBRE INT(4)
		 );
		 
CREATE TABLE MEMBRE
        (ID INT(4) PRIMARY KEY,
         PRENOM VARCHAR(32),
         NOM VARCHAR(32),
         DATEN DATE ,
         GENRE CHAR(1),
         IDCOMPTE INT(4) NOT NULL,
         IDHOTE INT(4),
         CONSTRAINT MEMBRE_IDCOMPTE FOREIGN KEY (IDCOMPTE) REFERENCES COMPTE (ID),
         CONSTRAINT MEMBRE_IDMEMBRE FOREIGN KEY (IDHOTE) REFERENCES MEMBRE (ID),
         CONSTRAINT CHK_GENRE CHECK (GENRE = 'M' OR GENRE = 'F' OR GENRE = NULL)
		 );
		 
ALTER TABLE compte ADD CONSTRAINT COMPTE_IDMEMBRE FOREIGN KEY (IDMEMBRE) REFERENCES MEMBRE (ID);
		 
CREATE TABLE COCKTAIL
        (ID INT(4) PRIMARY KEY,
         INTITULE VARCHAR(255) NOT NULL,
         ILLUSTRATIONURL VARCHAR(255),
		 	CATEGORIE VARCHAR(255) NOT NULL,
		 	DESCRIPTION TEXT,
         FORCEALC INT(2),
         CONSTRAINT CHK_CATEGORIE CHECK (CATEGORIE = 'Apéritif' OR CATEGORIE = 'Digestif' OR CATEGORIE = 'Apéritif/Digestif')
		 );
		
CREATE TABLE INGREDIENT
        (ID INT(4) PRIMARY KEY,
         INTITULE VARCHAR(255) NOT NULL,
         DEGREALCOOL INT(2)
		 );
		 
CREATE TABLE CONTENIR
        (IDCOCKTAIL INT(4) ,
		 	IDINGREDIENT INT(4) ,
		  QUANTITE INT(2) NOT NULL,
		 	UNITE VARCHAR(16),
		 	CONSTRAINT CONTENIR_IDCOCKTAIL FOREIGN KEY (IDCOCKTAIL) REFERENCES COCKTAIL (ID),
		 	CONSTRAINT CONTENIR_IDINGREDIENT FOREIGN KEY (IDINGREDIENT) REFERENCES INGREDIENT (ID),
		 	primary key (IDCOCKTAIL,  IDINGREDIENT)
			);
		
CREATE TABLE NOTER
        (IDMEMBRE INT(4) ,
			IDCOCKTAIL INT(4) ,
		  NOTE INT(2) NOT NULL,
			CONSTRAINT NOTER_IDCOCKTAIL FOREIGN KEY (IDCOCKTAIL) REFERENCES COCKTAIL (ID),
			CONSTRAINT NOTER_IDMEMBRE FOREIGN KEY (IDMEMBRE) REFERENCES MEMBRE (ID),
			primary key (IDMEMBRE,  IDCOCKTAIL),
			CONSTRAINT CHK_NOTE CHECK (NOTE >= 0 AND NOTE <= 5)
			);
		
CREATE TABLE STOCKER
        (IDINGREDIENT INT(4),
			IDMEMBRE INT(4),
		  ENRESERVE TINYINT(1) NOT NULL,
			CONSTRAINT STOCKER_IDINGREDIENT FOREIGN KEY (IDINGREDIENT) REFERENCES INGREDIENT (ID),
			CONSTRAINT STOCKER_IDMEMBRE FOREIGN KEY (IDMEMBRE) REFERENCES MEMBRE (ID),
			primary key (IDMEMBRE,  IDINGREDIENT)
			);
		
CREATE TABLE PREFERENCE
		(IDINGREDIENT INT(4),
		IDMEMBRE INT(4),
		CONSTRAINT PREFERENCE_IDINGREDIENT FOREIGN KEY (IDINGREDIENT) REFERENCES INGREDIENT (ID),
		CONSTRAINT PREFERENCE_IDMEMBRE FOREIGN KEY (IDMEMBRE) REFERENCES MEMBRE (ID),
		primary key (IDMEMBRE,  IDINGREDIENT)
		);
		
CREATE TABLE PROPOSE
		(IDCOCKTAIL INT(4),
		IDMEMBRE INT(4),
		CONSTRAINT PROPOSE_IDCOCKTAIL FOREIGN KEY (IDCOCKTAIL) REFERENCES COCKTAIL (ID),
		CONSTRAINT PROPOSE_IDMEMBRE FOREIGN KEY (IDMEMBRE) REFERENCES MEMBRE (ID),
		primary key (IDMEMBRE,  IDCOCKTAIL)
		);
		
CREATE TABLE FAVORI
		(IDCOCKTAIL INT(4),
		IDMEMBRE INT(4),
		CONSTRAINT FAVORI_IDCOCKTAIL FOREIGN KEY (IDCOCKTAIL) REFERENCES COCKTAIL (ID),
		CONSTRAINT FAVORI_IDMEMBRE FOREIGN KEY (IDMEMBRE) REFERENCES MEMBRE (ID),
		primary key (IDMEMBRE,  IDCOCKTAIL)
		);
		
CREATE TABLE ETREAMI
		(IDMEMBRE1 INT(4),
		IDMEMBRE2 INT(4),
		CONSTRAINT ETREAMI_IDMEMBRE1 FOREIGN KEY (IDMEMBRE1) REFERENCES MEMBRE (ID),
		CONSTRAINT ETREAMI_IDMEMBRE2 FOREIGN KEY (IDMEMBRE2) REFERENCES MEMBRE (ID),
		primary key (IDMEMBRE1,  IDMEMBRE2)
		);	